name: Build Python package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v5

      # Set up Python
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'  # TODO: Take version from pyproject.toml?

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: poetry install --no-root

      # Build package
      - name: Build package
        run: poetry build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tm-tc-code-generator-dist
          path: dist/
